# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-09 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pw_hash',
            field=models.CharField(default='password', max_length=500),
            preserve_default=False,
        ),
    ]
